import { buildWindowsAgentHookPostCommand } from '../agent-hooks/installer-utils'
import {
  buildPosixHookPayloadCapture,
  buildPosixHookSpoolLines,
  buildWindowsHookEnvironmentGuardLines,
  buildWindowsHookStdinDrainEpilogue
} from '../agent-hooks/hook-stdin-contract'

export type CommandCodeManagedScriptTarget = 'local' | 'posix'

export function buildCommandCodeManagedScript(
  target: CommandCodeManagedScriptTarget = 'local'
): string {
  if (target === 'local' && process.platform === 'win32') {
    return [
      '@echo off',
      'setlocal',
      'if "%MANTA_AGENT_HOOK_PORT%"=="" if defined MANTA_AGENT_HOOK_ENDPOINT if exist "%MANTA_AGENT_HOOK_ENDPOINT%" call "%MANTA_AGENT_HOOK_ENDPOINT%" 2>nul',
      'if "%MANTA_AGENT_HOOK_TOKEN%"=="" if not "%MANTA_AGENT_HOOK_PORT%"=="" call :sourceEndpointByPort',
      ...buildWindowsHookEnvironmentGuardLines(),
      buildWindowsAgentHookPostCommand('command-code'),
      'exit /b 0',
      ':sourceEndpointByPort',
      'if not defined APPDATA exit /b 0',
      'if exist "%APPDATA%\\manta-dev\\agent-hooks" for /r "%APPDATA%\\manta-dev\\agent-hooks" %%F in (endpoint.cmd) do call :maybeSourceEndpoint "%%~fF"',
      'if "%MANTA_AGENT_HOOK_TOKEN%"=="" if exist "%APPDATA%\\manta\\agent-hooks" for /r "%APPDATA%\\manta\\agent-hooks" %%F in (endpoint.cmd) do call :maybeSourceEndpoint "%%~fF"',
      'exit /b 0',
      ':maybeSourceEndpoint',
      'if not "%MANTA_AGENT_HOOK_TOKEN%"=="" exit /b 0',
      'for /f "tokens=2 delims==" %%P in (\'findstr /b /c:"set MANTA_AGENT_HOOK_PORT=" "%~1" 2^>nul\') do if "%%P"=="%MANTA_AGENT_HOOK_PORT%" call "%~1" 2>nul',
      'exit /b 0',
      ...buildWindowsHookStdinDrainEpilogue(),
      ''
    ].join('\r\n')
  }

  return [
    '#!/bin/sh',
    ...buildPosixHookPayloadCapture(),
    ...buildPosixHookSpoolLines('command-code'),
    '__manta_read_ancestor_var() {',
    '  __manta_name="$1"',
    '  __manta_pid="${PPID:-}"',
    '  while [ -n "$__manta_pid" ] && [ "$__manta_pid" != "0" ] && [ "$__manta_pid" != "1" ]; do',
    '    __manta_value=""',
    '    if [ -r "/proc/$__manta_pid/environ" ]; then',
    '      __manta_value=$(tr "\\000" "\\n" < "/proc/$__manta_pid/environ" 2>/dev/null | sed -n "s/^${__manta_name}=//p" | head -n 1)',
    '    fi',
    '    if [ -z "$__manta_value" ]; then',
    '      __manta_value=$(ps eww -p "$__manta_pid" -o command= 2>/dev/null | tr " " "\\n" | sed -n "s/^${__manta_name}=//p" | head -n 1)',
    '    fi',
    '    if [ -n "$__manta_value" ]; then',
    '      printf "%s\\n" "$__manta_value"',
    '      return 0',
    '    fi',
    '    __manta_pid=$(ps -o ppid= -p "$__manta_pid" 2>/dev/null | tr -d " ")',
    '  done',
    '  return 1',
    '}',
    '__manta_fill_from_ancestor() {',
    '  __manta_name="$1"',
    '  case "$__manta_name" in',
    '    MANTA_AGENT_HOOK_ENDPOINT) [ -z "${MANTA_AGENT_HOOK_ENDPOINT:-}" ] || return 0 ;;',
    '    MANTA_AGENT_HOOK_PORT) [ -z "${MANTA_AGENT_HOOK_PORT:-}" ] || return 0 ;;',
    '    MANTA_AGENT_HOOK_TOKEN) [ -z "${MANTA_AGENT_HOOK_TOKEN:-}" ] || return 0 ;;',
    '    MANTA_AGENT_HOOK_ENV) [ -z "${MANTA_AGENT_HOOK_ENV:-}" ] || return 0 ;;',
    '    MANTA_AGENT_HOOK_VERSION) [ -z "${MANTA_AGENT_HOOK_VERSION:-}" ] || return 0 ;;',
    '    MANTA_PANE_KEY) [ -z "${MANTA_PANE_KEY:-}" ] || return 0 ;;',
    '    MANTA_TAB_ID) [ -z "${MANTA_TAB_ID:-}" ] || return 0 ;;',
    '    MANTA_WORKTREE_ID) [ -z "${MANTA_WORKTREE_ID:-}" ] || return 0 ;;',
    '    MANTA_AGENT_LAUNCH_TOKEN) [ -z "${MANTA_AGENT_LAUNCH_TOKEN:-}" ] || return 0 ;;',
    '    *) return 0 ;;',
    '  esac',
    '  __manta_value=$(__manta_read_ancestor_var "$__manta_name") || return 0',
    '  [ -n "$__manta_value" ] && export "$__manta_name=$__manta_value"',
    '}',
    '__manta_endpoint_value() {',
    '  __manta_endpoint_name="$1"',
    '  __manta_endpoint_path="$2"',
    '  sed -n "s/^${__manta_endpoint_name}=//p" "$__manta_endpoint_path" 2>/dev/null | head -n 1',
    '}',
    '__manta_fill_from_endpoint_file() {',
    '  __manta_endpoint_path="$1"',
    '  [ -r "$__manta_endpoint_path" ] || return 0',
    '  __manta_endpoint_port=$(__manta_endpoint_value MANTA_AGENT_HOOK_PORT "$__manta_endpoint_path")',
    '  if [ -n "${MANTA_AGENT_HOOK_PORT:-}" ] && [ -n "$__manta_endpoint_port" ] && [ "$__manta_endpoint_port" != "$MANTA_AGENT_HOOK_PORT" ]; then',
    '    return 0',
    '  fi',
    '  for __manta_endpoint_name in MANTA_AGENT_HOOK_PORT MANTA_AGENT_HOOK_TOKEN MANTA_AGENT_HOOK_ENV MANTA_AGENT_HOOK_VERSION; do',
    '    eval "__manta_current=\\${$__manta_endpoint_name:-}"',
    '    [ -z "$__manta_current" ] || continue',
    '    __manta_endpoint_value=$(__manta_endpoint_value "$__manta_endpoint_name" "$__manta_endpoint_path")',
    '    [ -n "$__manta_endpoint_value" ] && export "$__manta_endpoint_name=$__manta_endpoint_value"',
    '  done',
    '}',
    '# Why: Command Code sanitizes hook subprocess env. The parent TUI process',
    '# still has Manta pane/hook metadata, so recover it before posting.',
    'for __manta_name in MANTA_AGENT_HOOK_ENDPOINT MANTA_AGENT_HOOK_PORT MANTA_AGENT_HOOK_TOKEN MANTA_AGENT_HOOK_ENV MANTA_AGENT_HOOK_VERSION MANTA_PANE_KEY MANTA_TAB_ID MANTA_WORKTREE_ID MANTA_AGENT_LAUNCH_TOKEN; do',
    '  __manta_fill_from_ancestor "$__manta_name"',
    'done',
    'if [ -n "$MANTA_AGENT_HOOK_ENDPOINT" ] && [ -r "$MANTA_AGENT_HOOK_ENDPOINT" ]; then',
    '  __manta_fill_from_endpoint_file "$MANTA_AGENT_HOOK_ENDPOINT"',
    'fi',
    '# Why: Command Code strips TOKEN-like env vars before invoking hooks. If',
    '# MANTA_AGENT_HOOK_ENDPOINT was not exported into this PTY, recover the',
    '# matching endpoint file by the unstripped loopback port.',
    'if [ -z "$MANTA_AGENT_HOOK_TOKEN" ] && [ -n "$MANTA_AGENT_HOOK_PORT" ]; then',
    '  for endpoint in \\',
    '    "$HOME/Library/Application Support/manta-dev/agent-hooks"/*/endpoint.env \\',
    '    "$HOME/Library/Application Support/manta-dev/agent-hooks/endpoint.env" \\',
    '    "${XDG_CONFIG_HOME:-$HOME/.config}/manta-dev/agent-hooks"/*/endpoint.env \\',
    '    "${XDG_CONFIG_HOME:-$HOME/.config}/manta-dev/agent-hooks/endpoint.env" \\',
    '    "$HOME/Library/Application Support/manta/agent-hooks/endpoint.env" \\',
    '    "${XDG_CONFIG_HOME:-$HOME/.config}/manta/agent-hooks/endpoint.env"; do',
    '    [ -r "$endpoint" ] || continue',
    '    endpoint_port=$(sed -n "s/^MANTA_AGENT_HOOK_PORT=//p" "$endpoint" | head -n 1)',
    '    if [ "$endpoint_port" = "$MANTA_AGENT_HOOK_PORT" ]; then',
    '      __manta_fill_from_endpoint_file "$endpoint"',
    '      break',
    '    fi',
    '  done',
    'fi',
    'if [ -z "$MANTA_AGENT_HOOK_PORT" ] || [ -z "$MANTA_AGENT_HOOK_TOKEN" ] || [ -z "$MANTA_PANE_KEY" ]; then',
    '  spool_hook_event',
    '  exit 0',
    'fi',
    // Timeout caps best-effort hook posts if the local listener stalls.
    // Why: pipe payload to curl's stdin (`payload@-`) instead of an inline
    // `payload=$VALUE` arg, so tens-of-KB tool output stays off the curl
    // command line (EDR command-line false positives). Wire body is identical.
    'printf \'%s\' "$payload" | curl -sS -X POST "http://127.0.0.1:${MANTA_AGENT_HOOK_PORT}/hook/command-code" \\',
    '  --connect-timeout 0.5 --max-time 1.5 \\',
    '  -H "Content-Type: application/x-www-form-urlencoded" \\',
    '  -H "X-Manta-Agent-Hook-Token: ${MANTA_AGENT_HOOK_TOKEN}" \\',
    '  --data-urlencode "paneKey=${MANTA_PANE_KEY}" \\',
    '  --data-urlencode "tabId=${MANTA_TAB_ID}" \\',
    '  --data-urlencode "launchToken=${MANTA_AGENT_LAUNCH_TOKEN}" \\',
    '  --data-urlencode "worktreeId=${MANTA_WORKTREE_ID}" \\',
    '  --data-urlencode "env=${MANTA_AGENT_HOOK_ENV}" \\',
    '  --data-urlencode "version=${MANTA_AGENT_HOOK_VERSION}" \\',
    '  --data-urlencode "payload@-" >/dev/null 2>&1 || spool_hook_event',
    'exit 0',
    ''
  ].join('\n')
}
